// Generated by CoffeeScript 1.6.3
module.exports = function(port, secret, name) {
  var client, debug;
  debug = require('debug')('vertex-example');
  debug('name %s', name);
  client = require('vertex-client').create({
    uuid: name,
    context: {
      name: name
    },
    secret: 'secret',
    connect: {
      uri: "ws://localhost:" + port
    }
  });
  client.connect();
  document.onmousemove = function(e) {
    return client.socket.send(JSON.stringify({
      event: 'broadcast',
      data: {
        event: 'mousemove',
        x: e.x,
        y: e.y
      }
    }));
  };
  return client.socket.on('message', function(payload) {
    return debug(payload);
  });
};
