// Generated by CoffeeScript 1.6.3
module.exports = function(port, secret, name) {
  var chart, client, debug, xLine, yLine;
  debug = require('debug')('vertex-example');
  debug('name %s', name);
  client = require('vertex-client').create({
    context: {
      name: name
    },
    secret: 'secret',
    connect: {
      uri: "ws://localhost:" + port
    }
  });
  client.connect();
  document.onmousemove = function(e) {
    return client.socket.send(JSON.stringify({
      event: 'broadcast',
      data: {
        mouse: {
          x: e.x,
          y: e.y
        }
      }
    }));
  };
  chart = new SmoothieChart({
    grid: {
      strokeStyle: 'rgb(125, 0, 0)',
      fillStyle: 'rgb(60, 0, 0)',
      lineWidth: 1,
      millisPerLine: 250,
      verticalSections: 6
    },
    labels: {
      fillStyle: 'rgb(60, 0, 0)'
    }
  });
  chart.streamTo(document.getElementById("mycanvas"));
  chart.addTimeSeries(xLine = new TimeSeries, {
    strokeStyle: 'rgb(0, 255, 0)',
    fillStyle: 'rgba(0, 255, 0, 0.4)',
    lineWidth: 3
  });
  chart.addTimeSeries(yLine = new TimeSeries, {
    strokeStyle: 'rgb(255, 0, 255)',
    fillStyle: 'rgba(255, 0, 255, 0.3)',
    lineWidth: 3
  });
  return client.socket.on('message', function(payload) {
    var time, x, y, _ref;
    try {
      _ref = JSON.parse(payload).mouse, x = _ref.x, y = _ref.y;
      time = new Date().getTime();
      xLine.append(time, parseInt(x));
      return yLine.append(time, parseInt(y));
    } catch (_error) {}
  });
};
