// Generated by CoffeeScript 1.6.3
module.exports = function(port, secret) {
  var mouse;
  mouse = {
    controller: function(opts, callback) {
      return callback(null, {
        headers: {
          'Content-Type': 'text/javascript'
        },
        body: "(" + (require('./browser_client').toString()) + ").call(self, '" + port + "', '" + secret + "', '" + opts.query.name + "');"
      });
    },
    view: function(opts, callback) {
      var name;
      console.log({
        OPTS: opts
      });
      name = opts.query.name || 'Untitled';
      return callback(null, {
        headers: {
          'Content-Type': 'text/html'
        },
        body: "<div class='container'></div>\n\n\n<script src=\"/build.js\"></script>\n<script src=\"./controller?name=" + name + "\"></script>\n\n                <!-- sneak name into script view url query -->\n\n"
      });
    }
  };
  mouse.controller.$www = {};
  mouse.view.$www = {};
  return mouse;
};
