// Generated by CoffeeScript 1.6.3
var port, readFileSync, routes, secret;

port = 3001;

secret = 'secret';

readFileSync = require('fs').readFileSync;

routes = {
  'build.js': function(opts, callback) {
    return callback(null, {
      headers: {
        'Content-Type': 'text/javascript'
      },
      body: readFileSync("" + __dirname + "/../../build/build.js")
    });
  },
  controller: function(opts, callback) {
    return callback(null, {
      headers: {
        'Content-Type': 'text/javascript'
      },
      body: "(" + (require('./browser_client').toString()) + ").call(self, '" + port + "', '" + secret + "', '" + opts.query.name + "');"
    });
  },
  view: function(opts, callback) {
    var name;
    console.log({
      OPTS: opts
    });
    name = opts.query.name || 'Untitled';
    return callback(null, {
      headers: {
        'Content-Type': 'text/html'
      },
      body: "<canvas id=\"mycanvas\" width=\"400\" height=\"100\"></canvas>\n\n\n<script src=\"/build.js\"></script>\n<script src=\"/controller?name=" + name + "\"></script>\n\n                <!-- sneak name into script view url query -->\n\n"
    });
  }
};

routes['build.js'].$www = {};

routes.controller.$www = {};

routes.view.$www = {};

require('vertex')({
  secret: secret,
  listen: {
    port: port
  },
  www: {
    listen: {
      port: 3000
    },
    allowRoot: true,
    root: routes
  },
  log: {
    level: 'debug'
  }
});
