// Generated by CoffeeScript 1.6.3
var Client, client, debug;

debug = require('debug')('vertex-examples:basic_client');

Client = require('vertex-client');

client = Client.create({
  title: 'Vertex Client',
  uuid: 'e2abc7fe-f602-4112-9a14-010018253cbd',
  secret: 'secret',
  connect: {
    uri: 'ws://localhost:3001'
  },
  log: {
    level: 'debug'
  }
});

client.connect();

client.socket.on('message', function(payload) {
  return debug('message', payload);
});
