// Generated by CoffeeScript 1.6.3
var Client, client, debug, infinity, position, radius, uuid, x, y;

debug = require('debug')('vertex-examples:basic_client');

Client = require('vertex-client');

uuid = process.env.NAME || 'ClientZero';

client = Client.create({
  title: 'Vertex Client',
  uuid: uuid,
  context: {
    name: uuid
  },
  secret: 'secret',
  connect: {
    uri: 'ws://localhost:3001'
  },
  log: {
    level: 'debug'
  }
});

client.connect();

client.socket.on('message', function(payload) {});

x = 0;

y = 0;

position = {
  x: 300,
  y: 200
};

radius = {
  x: 200,
  y: 100
};

infinity = function() {
  return client.socket.send(JSON.stringify({
    event: 'broadcast',
    data: {
      event: 'mousemove',
      uuid: uuid,
      x: position.x + (radius.x * Math.cos(x++ / 20)),
      y: position.y + (radius.y * Math.sin(y++ / 10))
    }
  }));
};

setInterval(infinity, 10);
