// Generated by CoffeeScript 1.6.3
var port, readFileSync, routes, secret;

port = 3001;

secret = 'secret';

readFileSync = require('fs').readFileSync;

routes = {
  'build.js': function(opts, callback) {
    return callback(null, {
      headers: {
        'Content-Type': 'text/javascript'
      },
      body: readFileSync("" + __dirname + "/../build/build.js")
    });
  },
  mouse: require('./mouse/mouse_module').create(port, secret),
  viewport: require('./viewport/viewport_module').create(port, secret)
};

routes['build.js'].$www = {};

require('vertex').create({
  secret: 'wrong',
  secret: secret,
  listen: {
    port: port
  },
  www: {
    listen: {
      port: 3000
    },
    allowRoot: true,
    routes: routes
  }
});
