// Generated by CoffeeScript 1.6.3
module.exports.create = function(port, secret) {
  var viewport;
  viewport = {
    controller: function(opts, callback) {
      return callback(null, {
        headers: {
          'Content-Type': 'text/javascript'
        },
        body: "(" + (module.exports.browserClient.toString()) + ").call(self, '" + port + "', '" + secret + "', '" + opts.query.name + "');"
      });
    },
    view: function(opts, callback) {
      var name;
      name = opts.query.name || 'Untitled';
      return callback(null, {
        headers: {
          'Content-Type': 'text/html'
        },
        body: "<body>\n<script src=\"/build.js\"></script>\n<script src=\"./controller?name=" + name + "\"></script>\n</body>"
      });
    }
  };
  viewport.controller.$www = {};
  viewport.view.$www = {};
  return viewport;
};

module.exports.browserClient = function(port, secret, name) {
  var client;
  client = require('vertex-client').create({
    uuid: name,
    context: {
      name: name
    },
    secret: secret,
    connect: {
      uri: "ws://localhost:" + port
    }
  });
  client.connect();
  return alert('okgood');
};
