// Generated by CoffeeScript 1.6.3
var port, routes, secret;

port = 3001;

secret = 'secret';

routes = {
  module: {
    view: function(opts, callback) {
      return callback(null, {
        headers: {
          'Content-Type': 'text/html'
        },
        body: "\n<script src=\"/engine.io.js\"></script>\n<script src=\"/module/controller\"></script>\n"
      });
    },
    controller: function(opts, callback) {
      return callback(null, {
        headers: {
          'Content-Type': 'text/javascript'
        },
        body: "(" + (require('./browser_client').toString()) + ").call(self, '" + port + "', '" + secret + "');"
      });
    },
    "function": function(opts, callback) {
      console.log(opts);
      return callback(null, {
        '1': {
          subrecord: {
            'xx': {
              da: 'ta1'
            },
            'yy': {
              da: 'ta2'
            }
          }
        }
      });
    },
    missing: function(opts, callback) {
      return callback(null, {
        body: '',
        statusCode: 404
      });
    }
  }
};

routes.module.view.$www = {
  cache: true
};

routes.module.controller.$www = {
  cache: true
};

routes.module["function"].$www = {
  roles: ['admin']
};

routes.module.missing.$www = {};

require('vertex')({
  secret: secret,
  listen: {
    port: port
  },
  www: {
    listen: {
      port: 3000
    },
    allowRoot: true,
    root: routes
  },
  log: {
    level: 'debug'
  }
});
