// Generated by CoffeeScript 1.6.3
var port, readFileSync, routes, secret;

port = 3001;

secret = 'secret';

readFileSync = require('fs').readFileSync;

routes = {
  'build.js': function(opts, callback) {
    return callback(null, {
      headers: {
        'Content-Type': 'text/javascript'
      },
      body: readFileSync("" + __dirname + "/../../build/build.js")
    });
  },
  'smoothie.js': function(opts, callback) {
    return callback(null, {
      headers: {
        'Content-Type': 'text/javascript'
      },
      body: readFileSync("" + __dirname + "/../../smoothie.js")
    });
  },
  controller: function(opts, callback) {
    return callback(null, {
      headers: {
        'Content-Type': 'text/javascript'
      },
      body: "(" + (require('./browser_client').toString()) + ").call(self, '" + port + "', '" + secret + "');"
    });
  },
  view: function(opts, callback) {
    return callback(null, {
      headers: {
        'Content-Type': 'text/html'
      },
      body: "\n<canvas id=\"mycanvas\" width=\"800\" height=\"200\"></canvas>\n\n\n<script src=\"/smoothie.js\"></script>\n<script src=\"/build.js\"></script>\n<script src=\"/controller\"></script>\n\n"
    });
  }
};

routes['build.js'].$www = {};

routes['smoothie.js'].$www = {};

routes.controller.$www = {};

routes.view.$www = {};

require('vertex')({
  secret: secret,
  listen: {
    port: port
  },
  www: {
    listen: {
      port: 3000
    },
    allowRoot: true,
    root: routes
  },
  log: {
    level: 'debug'
  }
});
