// Generated by CoffeeScript 1.6.3
var Client, client;

Client = require('vertex-client');

client = Client.create({
  title: 'Vertex Client',
  uuid: 'e2abc7fe-f602-4112-9a14-010018253cbd',
  secret: 'π',
  connect: {
    uri: 'ws://localhost:3001'
  },
  log: {
    level: 'debug'
  }
});

client.connect();
