// Generated by CoffeeScript 1.6.3
module.exports = function(port, secret) {
  var socket;
  socket = eio("ws://localhost:" + port);
  socket.onopen = function() {
    return socket.send("1" + (JSON.stringify({
      event: 'handshake',
      data: {
        title: 'Client',
        uuid: 'UUID',
        context: {},
        secret: secret
      }
    })));
  };
  socket.onmessage = function(msg) {
    var obj;
    obj = JSON.parse(msg.data.substr(1));
    return console.log(obj);
  };
  return socket.onclose = function() {};
};
