// Generated by CoffeeScript 1.6.3
module.exports = function(port, secret) {
  var client;
  client = require('vertex-client').create({
    connect: {
      uri: "ws://localhost:" + port
    }
  });
  return client.connect();
};
