// Generated by CoffeeScript 1.6.3
module.exports = function(port, secret) {
  var client;
  client = require('vertex-client').create({
    secret: 'secret',
    connect: {
      uri: "ws://localhost:" + port
    }
  });
  client.connect();
  return document.onmousemove = function(e) {
    return client.socket.send(JSON.stringify({
      event: 'broadcast',
      data: {
        mouse: {
          x: e.x,
          y: e.y
        }
      }
    }));
  };
};
